var lang = sessionStorage.getItem("lang") ? sessionStorage.getItem("lang") : "EN";
var languageTexts = {
    "EN": {
        // INDEX
        "Inductive-Power-Supply": "Inductive-Power-Supply",
        "Monitor": "Monitor",
        "Settings": "Settings",
        "Logging": "Logging",
        "Year": "Year",
        "Month": "Month",
        "Day": "Day",
        "Hour": "Hour",
        "Min": "Min",
        "Debug": "Debug",
        "Warning": "Warning",
        "index-warning-info-box": "Warning are not self-resetting. Warnings can can be reset via 'Setting' tab or by",
        "Id": "Id",
        "Description": "Description",
        "Status": "Status",
        "Heat-Sink Temperature": "Heat-Sink Temperature",
        "IM-Pad Temperature": "IM-Pad Temperature",
        "RTC Byttery Low Voltage": "RTC Byttery Low Voltage",
        "index-error-warning-box": "Errors are not self-resetting. Only errors with 'i' are cleard after conditiondisappears. All permanent  errors can can be reset via 'Setting' tab or by Ethernet command",
        "Status": "Status",
        "Power Good": "Power Good",
        "Over Current": "Over Current",
        "Over Temperature": "Over Temperature",
        "Fan Fault": "Fan Fault",
        "Heat-Sink Temperature": "Heat-Sink Temperature",
        "IM-Pad Temperature": "IM-Pad Temperature",
        "RTC Battery Voltage": "RTC Battery Voltage",
        "EEPROM Read/Write": "EEPROM Read/Write",
        "MRAM Read/Write": "MRAM Read/Write",
        "Parameter": "Parameter",
        "This error is self-resetting.": "This error is self-resetting.",
        "Over Voltage": "Over Voltage",
        "This error is self-resetting.": "This error is self-resetting.",
        "PLC Controller": "PLC Controller",
        "plccontroller-info-box": "In 'BMS & PLC' mode from BMS requested set values can be manipulated by PLC  multiplicator and offset.",
        "Equation": "Equation",
        "Value": "Value",
        "Unit": "Unit",
        "Command": "Command",
        "State": "State",
        "Stop": "Stop",
        "Enable": "Enable",
        "Set value": "Set value",
        "Current": "Current",
        "Voltage": "Voltage",
        "Multiplicator": "Multiplicator",
        "Current": "Current",
        "Voltage": "Voltage",
        "Offset": "Offset",
        "Current": "Current",
        "Voltage": "Voltage",
        "BMS: Battery Management System": "BMS: Battery Management System",

        "Release": "Release",
        "Charging current": "Charging current",
        "Charging voltage": "Charging voltage",
        "State": "State",
        "SOC: state of charge": "SOC: state of charge",
        "Battery voltage": "Battery voltage",
        "Cell temperature": "Cell temperature",
        "Power Management": "Power Management",
        "Descripton": "Descripton",
        "Mode": "Mode",
        "Charging mode": "Charging mode",
        "Manual": "Manual",
        "BMS only": "BMS only",
        "SBMS & PLCec": "BMS & PLC",
        "PLC only": "PLC only",
        "BMS type": "BMS type",
        "Can": "Can",
        "Can Open": "Can Open",
        "Set value<": "Set value<",
        "Current": "Current",
        "Voltage": "Voltage",
        "Power": "Power",
        "index-power-info-box": "The set value is an internal value calculated from voltage and current. The output is limited to 3kW and thereforethe set value may not correspond to the output value. The reason for the reduction is given with the value 'Derating reason'",
        "Output": "Output",
        "Current": "Current",
        "Derating reason": "Derating reason",
        "None": "None",
        "Set value limit": "Set value limit",
        "Start phase": "Start phase",
        "End of charge voltage<": "End of charge voltage<",
        "IM-Pad temperature": "IM-Pad temperature",
        "Head-Sink temperature": "Head-Sink temperature",
        "Power": "Power",
        "Error": "Error",
        "Disable": "Disable",
        "Power transfer": "Power transfer",
        "Disabled": "Disabled",
        "Active": "Active",
        "PWM duty": "PWM duty",
        "Fan": "Fan",
        "Duty": "Duty",
        "Measurement": "Measurement",
        "Descripton": "Descripton",
        "Battery": "Battery",
        "Current": "Current",
        "Voltage": "Voltage",
        "Power": "Power",
        "DC-Link": "DC-Link",
        "Voltage": "Voltage",
        "Temperature": "Temperature",
        "Heat-Sink": "Heat-Sink",
        "Frequency": "Frequency",
        "Rectifier pahse U": "Rectifier pahse U",
        "Misc": "Misc",
        "Fan voltage": "Fan voltage",
        "RTC battery voltage": "RTC battery voltage",
        "RTC: Real Time Clock": "RTC: Real Time Clock",
        "LED": "LED",
        "Name": "Name",
        "Status": "Status",
        "CAN Status": "CAN Status",
        "CAN bus deactivated.": "CAN bus deactivated.",
        "Can bus fault.": "Can bus fault.",
        "CAN bus recessive.": "CAN bus recessive.",
        "Receiving data": "Receiving data",
        "Sending data.": "Sending data.",
        "No charging process.": "No charging process.",
        "Fully charged.": "Fully charged.",
        "Charging process active.": "Charging process active.",
        "Module is ready for operation. Charging is not requested": "Module is ready for operation. Charging is not requested",
        "Charging is requested. Target value is sent to IPS.": "Charging is requested. Target value is sent to IPS.",
        "No warnings or faults.": "No warnings or faults.",
        "Fault in operation": "Fault in operation",
        "Fault without charging request.": "Fault without charging request.",
        "Warning in operation.": "Warning in operation.",
        "Warning without charging request.": "Warning without charging request.",
        "Software Information": "Software Information",
        "Bootloader": "Bootloader",
        "Version": "Version",
        "Build Date Time": "Build Date & Time",
        "Firmware": "Firmware",
        // SETTING
        "Monitor": "Monitor",
        "Logging": "Logging",
        "Debug": "Debug",
        "Error & Warning Reset": "Error & Warning Reset",
        "error-warning-reset-info-box": "Press the 'Reset' button to reset all errors and warnings. If the cause of theerror/warning is still present, the error/warning is generated again.",
        "Charging Power Management": "Charging Power Management",
        "Select charging mode": "Select charging mode",
        "Manual": "Manual",
        "BMS only": "BMS only",
        "BMS & PLC": "BMS & PLC",
        "PLC only": "PLC only",
        "Select BMS type": "Select BMS type",
        "Can": "Can",
        "Can Open": "Can Open",
        "Set output resistor": "Set output resistor",
        "Set current error correction": "Set current error correction [A]",
        "Set over voltage threshold": "Set over voltage threshold [V]",
        "Set": "Set",
        "Temperature Threshold": "Temperature Threshold",
        "Descripton": "Descripton",
        "Unit": "Unit",
        "IM-Pad error": "IM-Pad error",
        "IM-Pad warning": "IM-Pad warning",
        "Heat-Sink error": "Heat-Sink error",
        "Heat-Sink warning": "Heat-Sink warning",
        "Set IM-Pad error": "Set IM-Pad °T error [°C]",
        "Set IM-Pad warning": "Set IM-Pad °T warning [°C]",
        "Set Heat-Sink error ": "Set Heat-Sink °T error [°C]",
        "Set Heat-Sink warning": "Set Heat-Sink °T warning [°C]",
        "CAN Configuration": "CAN Configuration",
        "Actual Settings": "Actual Settings",
        "MPU CAN ID": "MPU CAN ID",
        "BMS CAN ID 1": "BMS CAN ID 1",
        "BMS CAN ID 2": "BMS CAN ID 2",
        "CAN Baudrate": "CAN Baudrate",
        "CAN ID Format": "CAN ID Format",
        "Edit CAN Settings": "Edit CAN Settings",
        "Edit MPU CAN ID 1": "Edit MPU CAN ID 1",
        "Edit MPU CAN ID 2": "Edit MPU CAN ID 2",
        "Edit BMS CAN ID 1": "Edit BMS CAN ID 1",
        "Edit BMS CAN ID 2": "Edit BMS CAN ID 2",
        " Edit CAN Baudrate": " Edit CAN Baudrate",
        "Edit CAN ID Format": "Edit CAN ID Format",
        "Configuration": "Configuration",
        "Network-relevant settings are only applied after a restart.": "Network-relevant settings are only applied after a restart.",
        "DHCP": "DHCP",
        "Static": "Static",
        "Dynamic": "Dynamic",
        "Descripton": "Descripton",
        "IP address": "IP address",
        "Subnet mask": "Subnet mask",
        "Gateway": "Gateway",
        "Hostname": "Hostname",
        "hostname-info-box": "If the device is in the same subnet like the client, it can be reached using the MDNS service via the web address <em>http://#hostname#/</em>. This is also the case if no DNS server is present.",
        "DNS server": "DNS server",
        "IP address": "IP address",
        "Subnet mask": "Subnet mask",
        "Gateway": "Gateway",
        "Hostname": "Hostname",
        "Up to 63 characters according to": "Up to 63 characters according to",
        "DNS server": "DNS server",
        "Ethernet Interface": "Ethernet Interface",
        "All 'PLC' and 'BMS & PLC' mode relevant settings only applied after a restart": "All 'PLC' and 'BMS & PLC' mode relevant settings only applied after a restart",
        "Descripton": "Description",
        "TCP MPU port": "TCP MPU port",
        "TCP Client port": "TCP Client port",
        "If port is set to 0, any port is accepted": "If port is set to 0, any port is accepted",
        "UDP MPU port": "UDP MPU port",
        "UDP Client port": "UDP Client port",
        "If port is set to 0, any port is accepted.": "If port is set to 0, any port is accepted.",
        "RX timeout": "RX timeout",
        "When this timeout expires, communication is considered lost. A value of 0ms means no timeout": "When this timeout expires, communication is considered lost. A value of 0ms means no timeout",
        "TCP MPU port": "TCP MPU port",
        "TCP client port": "TCP client port",
        "UDP MPU por": "UDP MPU por",
        "UDP client port": "UDP client port",
        "Set": "Set",
        "Can Interface": "Can Interface",
        "Some Can relevant settings only applied after a restart.": "Some Can relevant settings only applied after a restart.",
        "Bitrate": "Bitrate",
        "RX timeout ": "RX timeout ",
        "When this timeout expires, communication is considered lost. Timeout only defined for 'Can' mode and a value of 0ms means no timeout": "When this timeout expires, communication is considered lost. Timeout only defined for 'Can' mode and a value of 0ms means no timeout",
        "Bitrate": "Bitrate",
        "RX timeout [ms]": "RX timeout [ms]",
        "When this timeout expires, communication is considered lost. Timeout only defined for 'Can' mode and A value of 0ms disables the timeout.": "When this timeout expires, communication is considered lost. Timeout only defined for 'Can' mode and A value of 0ms disables the timeout.",
        "RTC: Real Time Clock": "RTC: Real Time Clock",
        "New RTC date & time": "New RTC date & time",
        "Product Information": "Product Information",
        "Descripton": "Descripton",
        "Name": "Name",
        "ID": "ID",
        "Production date": "Production date",
        "AC address": "AC address",
        "Firmware Restart": "Firmware Restart",
        "Restart firmeware": "Restart firmeware",
        "Firmware Update": "Firmware Update",
        "firmware-update-info-box": "Firmware update is managed by bootloader. Press the 'Reboot' button to switch to  bootloader mode. This restarts the CPU. It may take a few seconds before thebootloader can then be reached via its static IP <em>192.168.1.100</em>. The bootloader stays active            for ~5 min. If valid firmware is available after this time, it will be booted.",
        "Enter bootloader mode": "Enter bootloader mode",
        "Factory Reset": "Factory Reset",
        "Reset config to factory values": "Reset config to factory values",
        "Configuration File": "Configuration File",

        //LOGGING
        "server-side-logging-info-box": "A logging function is implemented in the MPU for diagnostic purposes. For this purpose information on the status of the MPU as well as errors and warnings are logged in a non-volatile memory. The logging can be started, stopped and read out via the web browser. When logging is running, the entries are live streamed into the below textarea.",

        "Name": "Name"

    },
    "DE": {

        "Inductive-Power-Supply": "Induktive-Power-Versorgung",
        "Monitor": "Monitor",
        "Setting": "Einstellungen",
        "Logging": "Loggen",
        "Year": "Jahr",
        "Month": "Monat",
        "Day": "Tag",
        "Hour": "Stunde",
        "Min": "Min",
        "Sec": "Sek",
        "Debug": "Debug",
        "Warning": "Warnung",
        "index-Warnung-info-box": "Warnungen setzen sich nicht selbst zurück. Warnungen können über 'Einstellungen' tab oder per Ethernet Befehl zurückgesetzt werden",
        "Id": "Id",
        "Description": "Beschreibung",
        "Status": "Status",
        "Heat-Sink Temperature": "Kühlkörpertemperatur",
        "IM-Pad Temperature": "IM-Pad Temperatur",
        "RTC Battery Low Voltage": "Niedrige Spannung der RTC-Batterie",
        "Index-Fehler-Warnungs-Box": "Warnungen setzen sich nicht selbst zurück. Nur Fehler mit einem 'i' werden gelöscht nach dem die Bedingung verschwindet. Alle permanenten Fehler können über 'Einstellungen' tab oder per Ethernet Befehl zurückgesetzt werden",
        "Status": "Status",
        "Power Good": "Power good",
        "Over Current": "Überstrom",
        "Over Temperature": "Over Temperature",
        "Fan Fault": "Lüfter Fehler",
        "Heat-Sink Temperature": "Kühlkörpertemperatur",
        "IM-Pad Temperature": "IM-Pad Temperatur",
        "RTC Battery Voltage": "Spannung der RTC-Batterie",
        "EEPROM Read/Write": "EEPROM lesen/schreiben",
        "MRAM Read/Write": "MRAM lesen/schreiben",
        "Parameter": "Parameter",
        "This error is self-resetting.": "Dieser Fehler setzt sich selbst zurück.",
        "Over Voltage": "Überspannung",
        "This error is self-resetting.": "Dieser Fehler setzt sich selbst zurück.",
        "PLC Controller": "PLC Controller",
        "Plccontroller-Info-Box": "Im BMS & PLC Modus können vom BMW angefragte festgelegte Werte per PLC Multiplikator und Versetzung manipuliert werden.",
        "Equation": "Gleichung",
        "Value": "Wert",
        "Unit": "Einheit",
        "Command": "Befehl",
        "State": "Zustand",
        "Stop": "Stop",
        "Enable": "Aktiviere",
        "Set value": "Wert bearbeiten",
        "Current": "Strom",
        "Voltage": "Spannung",
        "Multiplicator": "Multiplikator",
        "Current": "Strom",
        "Voltage": "Spannung",
        "Offset": "Versetzung",
        "Current": "Strom",
        "Voltage": "Spannung",
        "BMS: Battery Management System": "BMS: Batterie Verwaltungs System",

        "Release": "Freigabe",
        "Charging current": "Ladestrom",
        "Charging voltage": "Ladespannung",
        "State": "Zustand",
        "SOC: state of charge": "SOC: Ladezustand",
        "Battery voltage": "Batterie Spannung",
        "Cell temperature": "Zelltemperatur",
        "Power Management": "Power Verwaltung",
        "Descripton": "Beschreibung",
        "Mode": "Modus",
        "Charging mode": "Lademodus",
        "Manual": "Manuell",
        "BMS only": "Nur BMS",
        "SBMS & PLCec": "BMS & PLC",
        "PLC only": "Nur PLC",
        "BMS type": "BMS Typ",
        "Can": "Can",
        "Can Open": "Can öffnen",
        "Set value<": "Wert bearbeiten<",
        "Current": "Strom",
        "Voltage": "Spannung",
        "Power": "Power",
        "index-power-info-box": "Der festgelegte Wert ist ein durch Spannung und Strom berechneter interner Wert. Die Ausgabe ist auf 3kW limitiert und somit kann der festglegte Wert möglicherweise nicht mit dem ausgegebenen Wert korrespondieren. Der Grund für die Reduktion wird mit dem Wert 'Unterlastender Grund' gegeben",
        "Output": "Ausgabe",
        "Current": "Strom",
        "Derating reason": "Unterlastender Grund",
        "None": "Keine",
        "Set value limit": "Wertelimit bearbeiten",
        "Start phase": "Start Phase",
        "End of charge voltage<": "Ende der Ladespannung<",
        "IM-Pad temperature": "IM-Pad Temperatur",
        "Head-Sink temperature": "Kühlkörpertemperature",
        "Power": "Power",
        "Error": "Fehler",
        "Disable": "Deaktiviere",
        "Power transfer": "Power Übertragung",
        "Disabled": "Deaktiviert",
        "Active": "Aktiv",
        "PWM duty": "PWM Pflicht",
        "Fan": "Lüfter",
        "Duty": "Pflicht",
        "Measurement": "Messung",
        "Descripton": "Beschreibung",
        "Battery": "Batterie",
        "Current": "Strom",
        "Voltage": "Spannung",
        "Power": "Power",
        "DC-Link": "DC-Link",
        "Voltage": "Spannung",
        "Temperature": "Temperatur",
        "Heat-Sink": "Kühlkörper",
        "Frequency": "Frequenz",
        "Rectifier phase U": "Gleichrichter Phase U",
        "Misc": "Sonstige",
        "Fan voltage": "Lüfter Spannung",
        "RTC battery voltage": "RTC Batterie Spannung",
        "RTC: Real Time Clock": "RTC: Echtzeit Uhr",
        "LED": "LED",
        "Name": "Name",
        "Status": "Status",
        "CAN Status": "CAN Status",
        "CAN bus deactivated.": "CAN bus deaktiviert.",
        "Can bus fault.": "Can bus Fehler.",
        "CAN bus recessive.": "CAN bus rezessiv.",
        "Receiving data": "Empfange Daten",
        "Sending data.": "Sende Daten.",
        "No charging process.": "Kein Ladungs Prozess.",
        "Fully charged.": "Voll geladen.",
        "Charging process active.": "Lade Vorgang aktiv.",
        "Module is ready for operation. Charging is not requested": "Modul ist bereit für Operation. Laden wurde nicht angefragt",
        "Charging is requested. Target value is sent to IPS.": "Laden wurde nicht angefragt. Zielwert wurde an IPS gesendet.",
        "No warnings or faults.": "Keine Warnungen oder Fehler.",
        "Fault in operation": "Fehler in Operation",
        "Fault without charging request.": "Fehler ohne Lade Anfrage.",
        "Warning in operation.": "Warning in operation.",
        "Warning without charging request.": "Warnung ohne Lade Anfrage.",
        "Software Information": "Software Informationen",
        "Bootloader": "Bootloader",
        "Version": "Version",
        "Build Date Time": "Baudatum & -zeit",
        "Firmware": "Firmware",
        // SETTING
        "Monitor": "Monitor",
        "Logging": "Loggen",
        "Debug": "Debug",
        "Error & Warning Reset": "Fehler & Warnung zurücksetzen",
        "error-warning-reset-info-box": "Drücke den 'zurücksetzen' Knopf um alle Fehler und Warnungen zurückzusetzen. Wenn der Auslöser des Fehlers oder der Warnung noch present ist, wird der Fehler oder die Warnung erneut generiert.",
        "Charging Power Management": "Lade Power Verwaltung",
        "Select charging mode": "Wähle den Lademodus",
        "Manual": "Manuell",
        "BMS only": "Nur BMS",
        "BMS & PLC": "BMS & PLC",
        "PLC only": "Nur PLC",
        "Select BMS type": "Wähle den BMS Typ",
        "Can": "Can",
        "Can Open": "Can Öffnen",
        "Set output resistor": "Ausgangswiderstand bearbeiten",
        "Set current error correction": "Stromfehler Korrektur bearbeiten[A]",
        "Set over voltage threshold": "Überspannungs Schwelle bearbeiten [V]",
        "Set": "Bearbeiten",
        "Temperature Threshold": "Temperatur Schwelle",
        "Descripton": "Beschreibung",
        "Unit": "Einheit",
        "IM-Pad error": "IM-Pad Fehler",
        "IM-Pad warning": "IM-Pad Warnung",
        "Heat-Sink error": "Kühlkörper Fehler",
        "Heat-Sink warning": "Kühlkörper Warnung",
        "Set IM-Pad error": "Bearbeite IM-Pad Fehler",
        "Set IM-Pad warning": "Bearbeite IM-Pad Warnung",
        "Set Heat-Sink error ": "Bearbeite Kühlkörepr Fehler",
        "Set Heat-Sink warning": "Bearbeite Kühlkörper Warnung",
        "CAN Configuration": "CAN Konfiguration",
        "Actual Settings": "Aktuelle Einstellungen",
        "MPU CAN ID": "MPU CAN ID",
        "BMS CAN ID 1": "BMS CAN ID 1",
        "BMS CAN ID 2": "BMS CAN ID 2",
        "CAN Baudrate": "CAN Baudrate",
        "CAN ID Format": "CAN ID Format",
        "Edit CAN Settings": "Bearbeite CAN Einstellungen",
        "Edit MPU CAN ID 1": "Bearbeite MPU CAN ID 1",
        "Edit MPU CAN ID 2": "Bearbeite MPU CAN ID 2",
        "Edit BMS CAN ID 1": "Bearbeite BMS CAN ID 1",
        "Edit BMS CAN ID 2": "Bearbeite BMS CAN ID 2",
        " Edit CAN Baudrate": "Bearbeite CAN Baudrate",
        "Edit CAN ID Format": "Bearbeite CAN ID Format",
        "Configuration": "Konfiguration",
        "Network-relevant settings are only applied after a restart.": "Network-relevante Einstellungen werden erst nach einem Neustart übernommen.",
        "DHCP": "DHCP",
        "Static": "Statisch",
        "Dynamic": "Dynamisch",
        "Descripton": "Beschreibung",
        "IP address": "IP Adresse",
        "Subnet mask": "Subnetz Maske",
        "Gateway": "Gateway",
        "Hostname": "Hostname",
        "hostname-info-box": "Falls das Gerät im selben Subnetz wie der client ist, kann es über Webadresse '<em>http://#hostname#/</em>' durch MDNS Service erreicht werden. Dies trifft auch zu wenn kein DNS Server present ist.",
        "DNS server": "DNS Server",
        "IP address": "IP Adresse",
        "Subnet mask": "Subnetz Maske",
        "Gateway": "Gateway",
        "Hostname": "Hostname",
        "Up to 63 characters according to": "Bis zu 63 Zeichen entsprechend",
        "DNS server": "DNS server",
        "Ethernet Interface": "Ethernet Interface",
        "All 'PLC' and 'BMS & PLC' mode relevant settings only applied after a restart": "Alle 'PLC' und 'BMS & PLC' Modi relevanten Einstellungen werden erst nach einem Neustart übernommen",
        "Descripton": "Beschreibung",
        "TCP MPU port": "TCP MPU port",
        "TCP Client port": "TCP Client port",
        "If port is set to 0, any port is accepted": "Wenn der Port als 0 festgelegt wurde, wird jeder Port akzeptiert.",
        "UDP MPU port": "UDP MPU port",
        "UDP Client port": "UDP Client port",
        "If port is set to 0, any port is accepted.": "Wenn der Port als 0 festgelegt wurde, wird jeder Port akzeptiert.",
        "RX timeout": "RX timeout",
        "When this timeout expires, communication is considered lost. A value of 0ms means no timeout": "Wenn dieser timeout verfällt, gilt die Kommunikation als verloren. Ein Wert von 0ms bedeutet keinen Timeout",
        "TCP MPU port": "TCP MPU port",
        "TCP client port": "TCP client port",
        "UDP MPU port": "UDP MPU port",
        "UDP client port": "UDP client port",
        "Set": "Bearbeiten",
        "Can Interface": "Can Interface",
        "Some Can relevant settings only applied after a restart.": "Manche Can relevanten Einstellungen werden erst nach einem Neustart übernommen.",
        "Bitrate": "Bitrate",
        "RX timeout ": "RX timeout ",
        "When this timeout expires, communication is considered lost. Timeout only defined for 'Can' mode and a value of 0ms means no timeout": "Wenn dieser Timeout verfällt, gilt die Kommunikation als verloren. Timeout ist nur für den 'Can' Modus definiert und ein Wert von 0ms bedeutet kein timeout.",
        "Bitrate": "Bitrate",
        "RX timeout [ms]": "RX timeout [ms]",
        "When this timeout expires, communication is considered lost. Timeout only defined for 'Can' mode and A value of 0ms disables the timeout.": "Wenn dieser Timeout verfällt, gilt die Kommunikation als verloren. Timeout ist nur für den 'Can' Modus definiert und ein Wert von 0ms bedeutet kein timeout.",
        "RTC: Real Time Clock": "RTC: Echt Zeit Clock",
        "New RTC date & time": "Neue RTC Datum & Uhrzeit",
        "Product Information": "Produkt Information",
        "Descripton": "Beschreibung",
        "Name": "Name",
        "ID": "ID",
        "Production date": "Produktions Datum",
        "AC address": "AC Adresse",
        "Firmware Restart": "Firmware Neustart",
        "Restart firmeware": "Neustart firmeware",
        "Firmware Update": "Firmware Update",
        "firmware-update-info-box": "Das Firmware Update wird vom Bootloader verwaltet. Drücke die 'Reboot' Option um in den Bootloader Modus zu wechseln. Dieser wird den CPU neustarten. Es kann einige Sekunden dauern bevor der Bootloader über seine static IP '<em>192.168.1.100</em>' erreicht werden kann. Der Bootloader bleibt            für ~5min aktiv. Falls eine gültige Firmware nach dieser Zeit verfügbar ist, wird sie gebooted.",
        "Enter bootloader mode": "Bootloader Modus",
        "Factory Reset": "Werkseinstellungen",
        "Reset config to factory values": "Setze Konfigurationen auf Werkseinstellungen zurück",
        "Configuration File": "Konfigurationsdatei",

        //LOGGING
        "server-side-logging-info-box": "Eine Loggen Funktion ist für Diagnose Zwecke im MPU implementiert. Für diesen Zweck sind Informationen über den Zustand der MPU als auch Fehler und Warnungen in einem non-volatile Speicher geloggt. Das Loggen kann gestartet, gestoppt und über den Webbrowser ausgelesen werden. Wenn Loggen läuft, werden Einträge live in die untere Textebene übertragen.",

        "Name": "Name"
    }
};

function refreshLabels(lang) {
    console.log("refreshLabels", lang);
    const elementsWithLangKeyClass = document.querySelectorAll('[data-key]');

    for (let i = 0; i < elementsWithLangKeyClass.length; i++) {
        const element = elementsWithLangKeyClass[i];
        langKey = element.getAttribute('data-key');
        if (languageTexts[lang][langKey]) {
            element.textContent = languageTexts[lang][langKey];
        }
    }

    document.getElementById('sse_lang').textContent = lang;

}

function changeLang(lang) {
    sessionStorage.setItem("lang", lang);
    refreshLabels(lang);
}

function initLanguage() {

    console.log("initLanguage")
    lang = sessionStorage.getItem("lang") ? sessionStorage.getItem("lang") : "EN";
    refreshLabels(lang);
    document.getElementById('sse_lang').textContent = lang;
    document.body.style.display = 'block';
}
